name: Enforce Styleguide
on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Runs pnpm lint
        run: |
          npm i -g pnpm
          pnpm i
          pnpm check
